---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusion-cicd3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fusion-cicd3
  template:
    metadata:
      labels:
        app: fusion-cicd3
    spec:
      containers:
      - name: fusion-cicd3
        image: docker.io/pngigena/fusion-cicd3:latest
        ports:
        - containerPort: 80