---
apiVersion: apps/v2
kind: Deployment
metadata:
  name: web-fusion-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-fusion-v2
  template:
    metadata:
      labels:
        app: web-fusion-v2
    spec:
      containers:
      - name: web-fusion-v2
        image: docker.io/pngigena/fusion-web-cicd:3
        ports:
        - containerPort: 80