---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusion-cicd2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fusion-cicd2
  template:
    metadata:
      labels:
        app: fusion-cicd2
    spec:
      containers:
      - name: fusion-cicd2
        image: docker.io/pngigena/fusion-cicd2:2
        ports:
        - containerPort: 80