---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-png-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-png-1
  template:
    metadata:
      labels:
        app: simple-web-png1
    spec:
      containers:
      - name: webserver-simple
        image: docker.io/kostiscodefresh/gitops-simple-app:v1.0
        ports:
        - containerPort: 8080